resolver: lts-3.11

packages:
- '.'

extra-deps:
  - relational-record-0.1.2.0
  - relational-schemas-0.1.1.0
  - sql-words-0.1.3.1
  - HDBC-session-0.1.0.0
  - names-th-0.2.0.0
  - persistable-record-0.1.0.1
  - relational-query-0.6.3.0
  - relational-query-HDBC-0.3.1.0
  - HDBC-2.4.0.1
  - HDBC-postgresql-2.3.2.3

flags: {}

extra-package-dbs: []
