resolver: lts-3.12

packages:
- '.'
- hdbc-mysql/

extra-deps:
  - relational-record-0.1.2.0
  - relational-schemas-0.1.2.0
  - sql-words-0.1.3.1
  - HDBC-session-0.1.0.0
  - names-th-0.2.0.1
  - persistable-record-0.2.0.0
  - relational-query-0.7.0.0
  - relational-query-HDBC-0.4.0.0
  - HDBC-2.4.0.1
  - HDBC-postgresql-2.3.2.3
  - HDBC-sqlite3-2.3.3.1

flags: {}

extra-package-dbs: []
